### ISSUE TITLE
Certificate error for google play app

### ISSUE THREAD

**Issue by yaroslavryzhkov** [pmvs2022/labrabota11-gr13b-snews#38]
Android 5.0
Pixel 3.1

Problem: `Certificate assigned to application is not secure or using old version`

Any solutions?

**Comment by GlobusOffZeWorld** [comment]
we ar smol startap from minsk we hav no mani to deploi our progekt to gugle play sori we wil fix this soon

**Comment by yaroslavryzhkov** [comment]
you should mark issue as a potential vulnerability

**Comment by GlobusOffZeWorld** [comment]
no u

**Comment by P1l1gr1m** [comment]
solved, gudbye
